# Generated by Django 6.0.6 on 2026-06-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="createda_at",
            new_name="created_at",
        ),
    ]
