# Generated by Django 6.0.6 on 2026-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_rename_createda_at_subscription_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
