# Generated by Django 6.0.6 on 2026-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscription_is_trial_subscription_trial_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
