# Generated by Django 6.0.6 on 2026-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscription_last_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
