# Generated by Django 6.0.6 on 2026-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_alter_subscription_billing_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
